---
title: '**STOR 565: Machine Learning**'
geometry: margin=2
output:
  prettydoc::html_pretty:
    theme: tactile
  html_document:
    toc: yes
    df_print: paged
  pdf_document:
    toc: yes
---



<style type="text/css">

div {
color: #13294B;
}

#TOC {
  color: #519D78;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  color: #4B9CD3;
  background-color: #13294B;
}

a:link {
    color: #4B9CD3;
    text-decoration: none;
}

a:visited {
        text-decoration: none;
color: #4B9CD3;

}
a:hover {
color: #4B9CD3;
background-color: #13294B;
}

.main-container {
  max-width: 300px;
  margin-left: auto;
  margin-right: auto;
}

.column {
  float: left;
  width: 50%;
}

.row:after {
  content: "";
  display: table;
  clear: both;
} 

</style>

# **About the Course**

See the **[syllabus](Syllabi/565_Syllabus.pdf)** for details. Machine learning has become one of the most exciting research areas in recent years. In this **Python-based** course, we will explore fundamental algorithms, delve into supervised and unsupervised learning methods, and examine practical applications. Along the way, you’ll build hands-on projects, develop a deep understanding of model training and evaluation, and learn how to handle real-world data challenges. Topics covered by this course include but are not limited to:

1. Machine Learning Overview
2. Linear Models (Linear Regression; Logistic Regression; SVM)
3. Non-linear Models (Tree-based Methods; Kernel SVM; Neural Networks)
4. Clustering Methods
5. Matrix Factorization
6. Advanced topics

- Instructor: **[Yao Li](https://liyao880.github.io/yaoli/)**

- Teaching Assistant: **[Shaleni Kovach](https://stor.unc.edu/people/graduate-students/)** (shaleni@email.unc.edu)

- Grader: TBA
    
- Class: TTH 9:30 - 10:45AM, Gardner 105
    
- Office Hours:
    - Instructor Office Hours: W 2:00 - 3:00PM, Hanes 334
    - TA Office Hours: M 2:00 - 3:00PM, Hanes B5; F 10:00 - 11:00AM, [Zoom](https://unc.zoom.us/j/93257575122?pwd=LywvTesMTaVqsTa4jup4oFuLLQAc6j.1)


# **Course Material**

| Date | Lecture | Slides | Tutorial|
|------|-----------------------|-------:|----------:|
|Jan. 09| Welcome |[Slides](Lecture/Lecture_01_Course_Logistics.pdf)|[Tutorial 1](https://drive.google.com/file/d/1viFR80Iv3JdXyRrt2VoVUJPYYqRIpA42/view?usp=sharing) |
|Jan. 14| Overview || |
|Jan. 16| Review || |
|Jan. 21| Linear Regression  || |
|Jan. 23| Linear Regression Extension   || |
|Jan. 28| Logistic Regression || |
|Jan. 30| Model Assessment and Selection || |
|Feb. 04| LDA, QDA and KNN || |
|Feb. 06| Support Vector Machines || |
|Feb. 11| Kernel SVM || |
|Feb. 13| Principal Component Analysis || |
|Feb. 18| Project Proposal Discussion || |
|Feb. 20| Project Proposal Discussion || |
|Feb. 25| Clustering Methods || |
|Feb. 27| Tree-based Methods || |
|Mar. 04| Matrix Factorization I || |
|Mar. 06| Matrix Factorization II || |
|Mar. 11| Spring Break || |
|Mar. 13| Spring Break || |
|Mar. 18| Neural Networks || |
|Mar. 20| Neural Networks for CV || |
|Mar. 25| Neural Networks for NLP || |
|Mar. 27| Generative Models || |
|Apr. 01| Reinforcement Learning || |
|Apr. 03| Interpretable ML || |
|Apr. 08| Fairness || |
|Apr. 10| Guest Lecture || |
|Apr. 15| Final Presentation || |
|Apr. 17| Well-being Day || |
|Apr. 22| Final Presentation || |
|Apr. 24| Final Presentation || |


# **Homework Tracker**

All homework assignments are to be submitted via **[Canvas](https://edtech.unc.edu/service/canvas/)**. Late homework will receive a grade of **0**.

| Date assigned | Instructions | Due Date (Time) |
|----------|:--------:|:-------------:|
| Jan.09 | [HW1](https://drive.google.com/file/d/1F5CxMbhek9dYOAzNFmzMpxOZmrPrudcp/view?usp=sharing)([.ipynb](https://colab.research.google.com/drive/1VNUBQzZ2sF_DvuwS4U1CkvrP_FDENymY?usp=drive_link))  |  Jan.26 (11:59 PM) |
|   | [HW2]()([.ipynb]()) |   (11:59 PM) |
|  | [HW3]()([.ipynb]())  |  (11:59 PM) |
|   | [HW4]()([.ipynb]())  |   (11:59 PM) |
|   | [HW5]()([.ipynb]()) |  (11:59 PM) |
|          |        |           |

# **Final Project Details**

This course includes a final project in lieu of a final exam. Projects will be completed in groups of **four** and consist of:

- Project Proposal (10%)
- Project Presentation (30%)
- Project Paper (50%)
- Peer Review Score (10%)

## Group List

Please form the final project group before **Jan 22nd**, and sign up using the shared **[spreadsheet](https://docs.google.com/spreadsheets/d/1T_rsnt5cD0X_QC9QEMgYZbeVX9WT1WY71MeNs9jKF6I/edit?usp=sharing)**. Please don't modify the information of other groups.

## Four Parts Including Point Values

I will meet with each group to discuss the final project topic. Project topics can be:

- Solve an interesting or new problem with existing method
- Develop a new algorithm/model
- Compare state-of-the-art algorithms on some problems
- ...

**P1: Project Proposal** *(10 Points):* The project proposal is limited to 2-page (excluding reference) and contains:

- Problem to solve
- Review of existing studies in this field
- Your proposed method or Methods you would like to compare
- Evaluation metric
- Reference

See latex template at [link](https://drive.google.com/file/d/16uQ-fbVysshhh13xvnpNy5GYPAMcplDK/view?usp=sharing).

**P2: Project Presentation** *(30 Points):* All groups will present their final projects during the last three lectures. Every group member is expected to join the presentation. The length of the presentation depends on the number of groups (10–20min) and will be announced later.


**P3: Project Paper** *(50 Points):* Each team must submit a written project report. It is recommended to include a discussion of how your research work can be further extended. It is required to use the [NeurIPS Latex style files](https://media.neurips.cc/Conferences/NeurIPS2024/Styles.zip) and submit the report in PDF format. The report should be less than 8 pages without references (no minimum requirement).

**P4: Peer Score** *(10 Points):* Ten points of the final project is based on an average score measuring overall contribution as seen by you and the other members of your group. Each group member should score every person in their group on a continuous scale from 0 (Bad) to 10 (Good). Before the due date of the final paper, every member is required to submit the group scoring through the google survey link below. Your name and this information will remain private between me and you. If you fail to submit this group scoring before the deadline, 2 points penalty will be applied and I will give the other members a score of 10.

- [Peer Scoring](https://forms.gle/37W7kicacTGgTBEK9)

    
## Due Dates of Individual Parts

| Part | Description |Method (Location) of Submission| Due Date (Time) |
|------|-------------|-------------|---------------------:|
| P1  | Project Proposal | Canvas | Feb. 16 (11:59PM)|
|   | Proposal Meeting | Hanes 334 | Feb. 18 / Feb. 20 (9:30AM-10:45AM)|
| P2  | Presentation Slides |Canvas| Before the Presentation Day|
|   | Final Presentation|Class| Last 3 Lectures|
| P3  | Final Report|Canvas|Apr. 27 (11:59PM)|
| P4  | Peer Scoring|[Google Survey]()|Apr. 27 (11:59PM)|

# **Paper Presentation**

Check the **[paper list](https://docs.google.com/spreadsheets/d/1_ysOszh_k5-kOKs0iwn8OWYU_yE9st4GZvBk2uVE1hs/edit?usp=sharing)** for paper presentation opportunity.

# **Reading**

- **[An Introduction to Statistical Learning](https://www.statlearning.com/)**, by Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 
- **[Elements of Statistical Learning](https://hastie.su.domains/ElemStatLearn/)**, by Trevor Hastie, Robert Tibshirani, and Jerome Friedman.
- **[Foundations of machine learning](https://cs.nyu.edu/~mohri/mlbook/)**, by Mehryar Mohri, Afshin Rostamizadeh, and Ameet Talwalkar.
- **[Deep Learning](https://www.deeplearningbook.org/)**, by Ian Goodfellow, Yoshua Bengio, Aaron Courville. 


This page was last updated on `r Sys.time()` Eastern Time.
